JustStoreMVC/Areas/Admin/Controllers/CategoryController.cs
using JustStore.DataAccess.Data;
using JustStore.DataAccess.Repository.IRepository;
using JustStore.Models;
using JustStore.Utlity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace JustStoreMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Category> objectFromDB = _unitOfWork.Category.GetAll().ToList();
            return View(objectFromDB);
        }

        public IActionResult CreateNewCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateNewCategory(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The Display Order can`t exactly match the Name");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult EditCategory(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDBbyID = _unitOfWork.Category.GetFirstOrDefault(u => u.ID == id);
            if (CategoryFromDBbyID == null)
            {
                TempData["error"] = "Category wasn`t updated";
                return NotFound();
            }
            return View(CategoryFromDBbyID);
        }
        [HttpPost]
        public IActionResult EditCategory(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The Display Order can`t exactly match the Name");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult DeleteCategory(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDBbyID = _unitOfWork.Category.GetFirstOrDefault(u => u.ID == id);
            if (CategoryFromDBbyID == null)
            {
                return NotFound();
            }
            return View(CategoryFromDBbyID);
        }
        [HttpPost, ActionName("DeleteCategory")]
        public IActionResult DeleteCategoryPOST(int? id)
        {
            Category? CategoryFromDBbyID = _unitOfWork.Category.GetFirstOrDefault(u => u.ID == id);
            if (CategoryFromDBbyID == null)
            {
                TempData["error"] = "Category wasn`t deleted";
                return NotFound();
            }
            _unitOfWork.Category.Delete(CategoryFromDBbyID);
            _unitOfWork.save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

JustStoreMVC/Areas/Admin/Controllers/OrderController.cs
using JustStore.DataAccess.Repository.IRepository;
using JustStore.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Stripe.Climate;
using System.Diagnostics;
using JustStore.Utlity;
using JustStore.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Stripe;
using Stripe.Checkout;

namespace JustStoreMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM orderVM { get; set; }
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Details(int orderId)
        {
            orderVM = new()
            {
                OrderHeader = _unitOfWork.OrderHeader
                    .GetFirstOrDefault(u=>u.Id==orderId, includeProperties:"ApplicationUser"),
                OrderDetail=_unitOfWork.OrderDetail
                    .GetAll(u=>u.OrderHeaderId == orderId, includeProperties:"Product")
            };
            return View(orderVM);
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin+","+SD.Role_Employee)]
        public IActionResult UpdateOrderDetail(int id)
        {
            var OrderHeaderFromDB = _unitOfWork.OrderHeader
                .GetFirstOrDefault(u => u.Id == orderVM.OrderHeader.Id);

            OrderHeaderFromDB.Name = orderVM.OrderHeader.Name;
            OrderHeaderFromDB.PhoneNumber = orderVM.OrderHeader.PhoneNumber;
            OrderHeaderFromDB.StreetAdress = orderVM.OrderHeader.StreetAdress;
            OrderHeaderFromDB.City = orderVM.OrderHeader.City;
            OrderHeaderFromDB.State = orderVM.OrderHeader.State;
            OrderHeaderFromDB.PostalCode = orderVM.OrderHeader.PostalCode;
            if (!string.IsNullOrEmpty(orderVM.OrderHeader.Carrier))
            {
                OrderHeaderFromDB.Carrier = orderVM.OrderHeader.Carrier;
            }
            if (!string.IsNullOrEmpty(orderVM.OrderHeader.TrackingNumber))
            {
                OrderHeaderFromDB.TrackingNumber = orderVM.OrderHeader.TrackingNumber;
            }

            _unitOfWork.OrderHeader.Update(OrderHeaderFromDB);
            _unitOfWork.save();

            TempData["Success"] = "Order Details Updated Successfully";

            return RedirectToAction(nameof(Details), new {orderId = OrderHeaderFromDB.Id});
        }
        
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin+","+SD.Role_Employee)]
        public IActionResult StartProcessing(int id)
        {
            _unitOfWork.OrderHeader.UpdateStatus(orderVM.OrderHeader.Id, SD.StatusInProcess);
            _unitOfWork.save();
            TempData["Success"] = "Order Details Updated Successfully";
            return RedirectToAction(nameof(Details), new {orderId = orderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin+","+SD.Role_Employee)]
        public IActionResult ShipOrder(int id)
        {
            var orderHeader =_unitOfWork.OrderHeader.GetFirstOrDefault(u => 
                u.Id == orderVM.OrderHeader.Id);

            orderHeader.TrackingNumber = orderVM.OrderHeader.TrackingNumber;
            orderHeader.Carrier = orderVM.OrderHeader.Carrier;
            orderHeader.OrderStatus = SD.StatusShipped;
            orderHeader.ShippingDate = DateTime.Now;
            if(orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                orderHeader.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
            }

            _unitOfWork.OrderHeader.Update(orderHeader);
            _unitOfWork.save();
            TempData["Success"] = "Order Shipped Successfully";
            return RedirectToAction(nameof(Details), new {orderId = orderVM.OrderHeader.Id });
        }
        
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin+","+SD.Role_Employee)]
        public IActionResult CancleOrder(int id)
        {
            var orderHeader =_unitOfWork.OrderHeader.GetFirstOrDefault(u => 
                u.Id == orderVM.OrderHeader.Id);

            if(orderHeader.PaymentStatus == SD.PaymentStatusApproved) 
            {
                var options = new RefundCreateOptions
                {
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = orderHeader.PaymentIntentId
                };

                var service = new RefundService();
                Refund refund = service.Create(options);
                _unitOfWork.OrderHeader
                    .UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusRefunded);
            }
            else 
            {
                _unitOfWork.OrderHeader
                    .UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusCancelled);
            }

            _unitOfWork.save();
            TempData["Success"] = "Order Cancelled Successfully";
            return RedirectToAction(nameof(Details), new {orderId = orderVM.OrderHeader.Id });
        }

		[ActionName("Details")]
		[HttpPost]
		public IActionResult Details_PAY_NOW()
		{
			orderVM.OrderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => 
            u.Id == orderVM.OrderHeader.Id, includeProperties: "ApplicationUser");
			orderVM.OrderDetail = _unitOfWork.OrderDetail.GetAll(u => 
            u.OrderHeaderId == orderVM.OrderHeader.Id, includeProperties: "Product");

			//stripe logic
			var domain = Request.Scheme + "://" + Request.Host.Value + "/";
			var options = new SessionCreateOptions
			{
				SuccessUrl = domain + $"admin/order/PaymentConfirmation?orderHeaderId={orderVM.OrderHeader.Id}",
				CancelUrl = domain + $"admin/order/details?orderId={orderVM.OrderHeader.Id}",
				LineItems = new List<SessionLineItemOptions>(),
				Mode = "payment",
			};

			foreach (var item in orderVM.OrderDetail)
			{
				var sessionLineItem = new SessionLineItemOptions
				{
					PriceData = new SessionLineItemPriceDataOptions
					{
						UnitAmount = (long)(item.Price * 100), // $20.50 => 2050
						Currency = "uah",
						ProductData = new SessionLineItemPriceDataProductDataOptions
						{
							Name = item.Product.Title
						}
					},
					Quantity = item.Count
				};
				options.LineItems.Add(sessionLineItem);
			}


			var service = new SessionService();
			Session session = service.Create(options);
			_unitOfWork.OrderHeader.UpdateStripePaymentId(orderVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
			_unitOfWork.save();
			Response.Headers.Add("Location", session.Url);
			return new StatusCodeResult(303);
		}

		public IActionResult PaymentConfirmation(int orderHeaderId)
		{

			OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(u => 
            u.Id == orderHeaderId);
			if (orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
			{
				//this is an order by company

				var service = new SessionService();
				Session session = service.Get(orderHeader.SessionId);

				if (session.PaymentStatus.ToLower() == "paid")
				{
					_unitOfWork.OrderHeader.UpdateStripePaymentId(orderHeaderId, session.Id, session.PaymentIntentId);
					_unitOfWork.OrderHeader.UpdateStatus(orderHeaderId, orderHeader.OrderStatus, SD.PaymentStatusApproved);
					_unitOfWork.save();
				}


			}
			return View(orderHeaderId);
		}

		#region API CALLS
		[HttpGet]
        public IActionResult GetAll(string status)
        {
            IEnumerable<OrderHeader> ObjectsFromDb ;

            if(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee)) 
            {
                ObjectsFromDb = _unitOfWork.OrderHeader
                .GetAll(includeProperties: "ApplicationUser").ToList();
            }
            else 
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userID = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                ObjectsFromDb = _unitOfWork.OrderHeader.GetAll(u => 
                u.ApplicationUserId == userID, includeProperties: "ApplicationUser");
            }

			switch (status)
			{
				case "pending":
                    ObjectsFromDb = ObjectsFromDb.Where(u => u.PaymentStatus
                        == SD.PaymentStatusDelayedPayment);
					break;

				case "inprocess":
					ObjectsFromDb = ObjectsFromDb.Where(u => u.OrderStatus
					    == SD.StatusInProcess);
					break;

				case "completed":
					ObjectsFromDb = ObjectsFromDb.Where(u => u.OrderStatus
					    == SD.StatusShipped);
					break;

				case "approved":
					ObjectsFromDb = ObjectsFromDb.Where(u => u.OrderStatus
						== SD.StatusApproved);
					break;

				default:
					break;
			}


			return Json(new { data = ObjectsFromDb });
        } 
        #endregion
    }
}

JustStoreMVC/Areas/Admin/Controllers/UserController.cs
using JustStore.DataAccess.Data;
using JustStore.DataAccess.Repository.IRepository;
using JustStore.Models;
using JustStore.Models.ViewModels;
using JustStore.Utlity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace JustStoreMVC.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = SD.Role_Admin)]
	public class UserController : Controller
	{

		private readonly UserManager<IdentityUser> _um;
		private readonly RoleManager<IdentityRole> _rm;
		private readonly IUnitOfWork _unitOfWork;
		public UserController(IUnitOfWork unitOfWork, UserManager<IdentityUser> um,
			RoleManager<IdentityRole> rm)
		{
			_unitOfWork = unitOfWork;
			_um = um;
			_rm = rm;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult RoleManagment(string userId)
		{
			RoleManagmentVM RoleVM = new RoleManagmentVM()
			{
				ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == userId,
					includeProperties:"Company"),

                RoleList = _rm.Roles.Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Name
				}),

				CompanyList = _unitOfWork.Company.GetAll().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.Id.ToString()
				})
			};

			RoleVM.ApplicationUser.Role = _um.GetRolesAsync(_unitOfWork.ApplicationUser
				.GetFirstOrDefault(u => u.Id == userId)).GetAwaiter().GetResult().FirstOrDefault();
			return View(RoleVM);
		}

		[HttpPost]
		public IActionResult RoleManagment(RoleManagmentVM rmvm) 
		{
			string oldRole = _um.GetRolesAsync(_unitOfWork.ApplicationUser
				.GetFirstOrDefault(u => u.Id == rmvm.ApplicationUser.Id))
				.GetAwaiter().GetResult().FirstOrDefault();

            ApplicationUser applicationUser = _unitOfWork.ApplicationUser
				.GetFirstOrDefault(u => u.Id == rmvm.ApplicationUser.Id);

            if (!(rmvm.ApplicationUser.Role == oldRole)) 
			{

				if (rmvm.ApplicationUser.Role == SD.Role_Company) 
				{
					applicationUser.CompanyId = rmvm.ApplicationUser.CompanyId;
				}
				if(oldRole == SD.Role_Company) 
				{
					applicationUser.CompanyId = null;
				}

				_unitOfWork.ApplicationUser.Update(applicationUser);
				_unitOfWork.save();

				_um.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
				_um.AddToRoleAsync(applicationUser, rmvm.ApplicationUser.Role).GetAwaiter().GetResult();

			}
			else 
			{
				if(oldRole == SD.Role_Company && 
					applicationUser.CompanyId != rmvm.ApplicationUser.CompanyId) 
				{
					applicationUser.CompanyId = rmvm.ApplicationUser.CompanyId;
					_unitOfWork.ApplicationUser.Update(applicationUser);
					_unitOfWork.save();	
				}
			}

			return RedirectToAction(nameof(Index));
		}


		#region API CALLS
		[HttpGet]
		public IActionResult GetAll()
		{
            List<ApplicationUser> ObjectsFromDb = _unitOfWork.ApplicationUser
				.GetAll(includeProperties:"Company").ToList();
			 
			foreach (var p in ObjectsFromDb) 
			{
		
				p.Role = _um.GetRolesAsync(p).GetAwaiter().GetResult().FirstOrDefault();

				if(p.Company == null) { p.Company = new() {Name = "" }; }
			}
			return Json(new { data = ObjectsFromDb });
        }

		[HttpPost]
		public IActionResult LockUnlock([FromBody]string id)
		{
			var objFromDb = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == id);
			if (objFromDb == null) 
			{
                return Json(new { succes = false, message = "Error while Locking/Unloking" });
            }

			if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now) 
			{
				objFromDb.LockoutEnd = DateTime.Now;
			}
			else 
			{
				objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
			_unitOfWork.ApplicationUser.Update(objFromDb);
			_unitOfWork.save(); 
            return Json(new { success = true, message = "Operation successful"});

		}
		#endregion
	}
}

JustStoreMVC/ViewComponents/ShoppingCartViewComponent.cs
using JustStore.DataAccess.Repository.IRepository;
using JustStore.Utlity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace JustStoreMVC.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
                _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                if(HttpContext.Session.GetInt32(SD.SessionCart) == null) 
                {
                    HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCart
                        .GetAll(u => u.ApplicationUserId == claim.Value).Count());
                }
                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);

            }
        }
    }
}

JustStoreMVC/Views/Shared/_Layout.cshtml
@using JustStore.Utlity
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Just Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/JustStoreMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href = "//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand nav-item btn bg-dark" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/book.png" style="width:40px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <div>
                            <li class="nav-item btn bg-dark">
                                <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        </div>
                        <div class="px-2">
                            <li class="nav-item btn bg-dark">
                                <a class="nav-link text-white" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                            </li>
                         </div>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <div>
                                <li class="nav-item dropdown btn bg-dark">
                                    <a class="nav-link dropdown-toggle text-white " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Content Manegment
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-item">
                                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                                        </li>
                                        <li class="dropdown-item">
                                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                        </li> 

                                        <li><hr class="dropdown-divider"></li>

                                        <li class="dropdown-item">
                                            <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                        </li>

                                        <li class="dropdown-item">
                                            <a class="nav-link text-white" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                        </li>
                                    </ul>
                                </li>
                            </div>
                        }
                        
                        <div class="px-2">
                            <li class="nav-item btn bg-dark">
                                <a class="nav-link text-white" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>
                        </div>                          
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a asp-area="" asp-controller="Home" asp-action="Privacy" style="font-family: 'Vivaldi', monospace; font-size: 20px; line-height: 1.6; letter-spacing: 3px; text-align: justify; color: white;" onmouseover="this.style.textDecoration='underline'" onmouseout="this.style.textDecoration='none'">Made by Pereverten</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/y6om4ux82785fymn1ce93psv4z2vk17x7nwsdve5rf8kdyc8/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

JustStoreMVC/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">toastr.success('@TempData["success"]');</script>
}

@if (TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js">@TempData["success"]</script>
	<script type="text/javascript">toastr.error('@TempData["success"]');</script>

}